### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by alanpoon** [wapc/wapc-guest-tinygo#5]
__guest_request and __guest_response's operationptr increases in each invocation
In wapc_guest_go:
<img width="352" alt="wapc_guest_go" src="https://user-images.githubusercontent.com/8205468/123392386-946c3c80-d5cf-11eb-89c1-e1b470b59ae4.png">

In wapc_guest_rust: operationptr does not increase in each invocation
<img width="352" alt="wapc_guest_rust" src="https://user-images.githubusercontent.com/8205468/123392396-97672d00-d5cf-11eb-8b5f-1b10bf2c4536.png">

**Comment by pkedy** [comment]
@alanpoon Thanks for reporting this. Go/TinyGo is a garbage collected language which might explain this but I would expect at some point the ptr value to potentially return to a lower value. How long of a period of time did you run this?

**Comment by alanpoon** [comment]
For a few seconds

**Comment by pkedy** [comment]
@alanpoon After the few seconds did it crash or increase its memory pool size?

**Comment by alanpoon** [comment]
It didn't crush, this wasn't the root cause in my case.
